{
  "openapi": "3.0.3",
  "info": {
    "version": "1.2.0",
    "title": "NLP Sandbox PHI Annotator API",
    "contact": {
      "name": "NLP Sandbox Team",
      "email": "team@nlpsandbox.io",
      "url": "https://nlpsandbox.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://github.com/nlpsandbox/nlpsandbox-schemas/blob/main/LICENSE"
    },
    "x-logo": {
      "url": "https://nlpsandbox.github.io/nlpsandbox-schemas/logo.png"
    },
    "description": "# Introduction\nA protected health information (PHI) annotator implements several endpoints that take as input a clinical note and outputs a list of predicted PHI annotations found in the clinical note. This OpenAPI document describes the specification of the NLP Sandbox PHI Annotator API. This specification includes the schemas of the input and output data, and the requirements that this annotator must meet if you want to benchmark its performance on [nlpsandbox.io](https://nlpsandbox.io).\n# Getting Started\nThe GitHub repository [nlpsandbox/phi-annotator-example](https://github.com/nlpsandbox/phi-annotator-example) provides an example implementation of the NLP Sandbox PHI Annotator API in Python-Flask. By the end of the tutorial available in the README, you will have built a Docker image for this NLP Sandbox tool. You will then be able to submit this image to [nlpsandbox.io](https://nlpsandbox.io) to benchmark its performance.\n# Benchmarking Requirements\nYour NLP Sandbox tool must meet the following requirements before evaluating its performance on [nlpsandbox.io](https://nlpsandbox.io).\n- The endpoint `/` must redirect to `/api/v1/tool`.\n- The endpoint `/ui` must redirect to the Swagger User Interface (UI).\n- The output of this tool must be reproducible: a given input should always\n  generate the same output.\n\n- To ensure the results are reproducible and robust, and the data are\n  secured, this tool must not connect to any remote server. When benchmarked\n  on [nlpsandbox.io](https://nlpsandbox.io), this tool will not be able to\n  connect to remote servers.\n\n# Examples\n- [NLP Sandbox PHI Annotator Example (Python)](https://github.com/nlpsandbox/phi-annotator-example)\n"
  },
  "tags": [
    {
      "name": "HealthCheck",
      "description": "Operations about health checks"
    },
    {
      "name": "TextContactAnnotation",
      "description": "Operations about text contact annotations"
    },
    {
      "name": "TextDateAnnotation",
      "description": "Operations about text date annotations"
    },
    {
      "name": "TextIdAnnotation",
      "description": "Operations about text ID annotations"
    },
    {
      "name": "TextPersonNameAnnotation",
      "description": "Operations about text person name annotations"
    },
    {
      "name": "TextLocationAnnotation",
      "description": "Operations about text location annotations"
    },
    {
      "name": "Tool",
      "description": "Operations about this tool"
    }
  ],
  "servers": [
    {
      "url": "http://example.com/api/v1"
    },
    {
      "url": "https://example.com/api/v1"
    }
  ],
  "paths": {
    "/healthCheck": {
      "get": {
        "tags": [
          "HealthCheck"
        ],
        "summary": "Get health check information",
        "description": "Get information about the health of the service",
        "operationId": "getHealthCheck",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HealthCheck"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/textContactAnnotations": {
      "post": {
        "tags": [
          "TextContactAnnotation"
        ],
        "summary": "Annotate contact information in a clinical note",
        "description": "Return the contact annotations found in a clinical note",
        "operationId": "createTextContactAnnotations",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TextContactAnnotationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TextContactAnnotationResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/textDateAnnotations": {
      "post": {
        "tags": [
          "TextDateAnnotation"
        ],
        "summary": "Annotate dates in a clinical note",
        "description": "Return the date annotations found in a clinical note",
        "operationId": "createTextDateAnnotations",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TextDateAnnotationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TextDateAnnotationResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/textIdAnnotations": {
      "post": {
        "tags": [
          "TextIdAnnotation"
        ],
        "summary": "Annotate IDs in a clinical note",
        "description": "Return the ID annotations found in a clinical note",
        "operationId": "createTextIdAnnotations",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TextIdAnnotationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TextIdAnnotationResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/textLocationAnnotations": {
      "post": {
        "tags": [
          "TextLocationAnnotation"
        ],
        "summary": "Annotate locations in a clinical note",
        "description": "Return the location annotations found in a clinical note",
        "operationId": "createTextLocationAnnotations",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TextLocationAnnotationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TextLocationAnnotationResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/textPersonNameAnnotations": {
      "post": {
        "tags": [
          "TextPersonNameAnnotation"
        ],
        "summary": "Annotate person names in a clinical note",
        "description": "Return the person name annotations found in a clinical note",
        "operationId": "createTextPersonNameAnnotations",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/TextPersonNameAnnotationRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TextPersonNameAnnotationResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/BadRequest"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/tool": {
      "get": {
        "tags": [
          "Tool"
        ],
        "summary": "Get tool information",
        "description": "Get information about the tool",
        "operationId": "getTool",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Tool"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    },
    "/tool/dependencies": {
      "get": {
        "tags": [
          "Tool"
        ],
        "summary": "Get tool dependencies",
        "description": "Get the dependencies of this tool",
        "operationId": "getToolDependencies",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ToolDependencies"
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/NotFound"
          },
          "500": {
            "$ref": "#/components/responses/InternalServerError"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "HealthCheck": {
        "type": "object",
        "description": "Represents the health of a service",
        "properties": {
          "status": {
            "description": "Indicates whether the service status is acceptable or not",
            "type": "string",
            "enum": [
              "pass",
              "fail",
              "warn"
            ]
          }
        },
        "required": [
          "status"
        ]
      },
      "Error": {
        "type": "object",
        "description": "Problem details (tools.ietf.org/html/rfc7807)",
        "properties": {
          "title": {
            "type": "string",
            "description": "A human readable documentation for the problem type"
          },
          "status": {
            "type": "integer",
            "description": "The HTTP status code"
          },
          "detail": {
            "type": "string",
            "description": "A human readable explanation specific to this occurrence of the problem"
          },
          "type": {
            "type": "string",
            "description": "An absolute URI that identifies the problem type"
          }
        },
        "required": [
          "title",
          "status"
        ]
      },
      "NoteId": {
        "description": "The ID of the clinical note",
        "type": "string",
        "minLength": 3,
        "maxLength": 60,
        "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
        "example": "awesome-note"
      },
      "PatientId": {
        "description": "The ID of the FHIR patient",
        "type": "string",
        "minLength": 3,
        "maxLength": 60,
        "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$",
        "example": "awesome-patient"
      },
      "Note": {
        "type": "object",
        "description": "A clinical note",
        "properties": {
          "identifier": {
            "$ref": "#/components/schemas/NoteId"
          },
          "text": {
            "description": "The content of the clinical note",
            "type": "string"
          },
          "type": {
            "description": "The note type (LOINC concept)",
            "type": "string"
          },
          "patientId": {
            "$ref": "#/components/schemas/PatientId"
          }
        },
        "required": [
          "identifier",
          "text",
          "type",
          "patientId"
        ],
        "example": {
          "identifier": "awesome-note",
          "text": "On 12/26/2020, Ms. Chloe Price met with Dr. Prescott in Seattle.",
          "type": "loinc:LP29684-5",
          "patientId": "awesome-patient"
        }
      },
      "TextContactAnnotationRequest": {
        "type": "object",
        "description": "A request to annotate contacts in a clinical note",
        "properties": {
          "note": {
            "$ref": "#/components/schemas/Note"
          }
        },
        "required": [
          "note"
        ],
        "example": {
          "note": {
            "identifier": "awesome-note",
            "text": "On 12/26/2020, Ms. Chloe Price met with Dr. Prescott in Seattle. Her phone number is 203-555-4545.\n",
            "type": "loinc:LP29684-5",
            "patientId": "awesome-patient"
          }
        }
      },
      "TextAnnotation": {
        "type": "object",
        "description": "An annotation in a text",
        "properties": {
          "start": {
            "description": "The position of the first character",
            "type": "integer"
          },
          "length": {
            "description": "The length of the annotation",
            "type": "integer"
          },
          "text": {
            "description": "The string annotated",
            "type": "string"
          },
          "confidence": {
            "description": "The confidence in the accuracy of the annotation",
            "type": "number",
            "format": "float",
            "minimum": 0,
            "maximum": 100
          }
        },
        "required": [
          "start",
          "length",
          "text",
          "confidence"
        ],
        "example": {
          "start": 42,
          "length": 19,
          "text": "the annotation text",
          "confidence": 95.5
        }
      },
      "TextContactAnnotation": {
        "type": "object",
        "description": "A contact annotation in a text",
        "allOf": [
          {
            "$ref": "#/components/schemas/TextAnnotation"
          },
          {
            "type": "object",
            "properties": {
              "contactType": {
                "description": "Type of contact information",
                "type": "string",
                "enum": [
                  "email",
                  "fax",
                  "ip_address",
                  "phone",
                  "url",
                  "other"
                ]
              }
            },
            "required": [
              "contactType"
            ]
          }
        ],
        "example": {
          "start": 42,
          "length": 11,
          "text": "dave@uw.edu",
          "contactType": "email",
          "confidence": 95.5
        }
      },
      "TextContactAnnotationResponse": {
        "type": "object",
        "description": "The response to a contact annotation request",
        "properties": {
          "textContactAnnotations": {
            "description": "A list of contact annotations",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TextContactAnnotation"
            }
          }
        },
        "required": [
          "textContactAnnotations"
        ]
      },
      "TextDateAnnotationRequest": {
        "type": "object",
        "description": "A request to annotate dates in a clinical note",
        "properties": {
          "note": {
            "$ref": "#/components/schemas/Note"
          }
        },
        "required": [
          "note"
        ]
      },
      "TextDateAnnotation": {
        "type": "object",
        "description": "A date annotation in a text",
        "allOf": [
          {
            "$ref": "#/components/schemas/TextAnnotation"
          },
          {
            "type": "object",
            "properties": {
              "dateFormat": {
                "description": "Date format (ISO 8601)",
                "type": "string",
                "example": "MM/DD/YYYY"
              }
            }
          }
        ],
        "example": {
          "start": 42,
          "length": 10,
          "text": "10/26/2020",
          "dateFormat": "MM/DD/YYYY",
          "confidence": 95.5
        }
      },
      "TextDateAnnotationResponse": {
        "type": "object",
        "description": "The response to a dates annotation request",
        "properties": {
          "textDateAnnotations": {
            "description": "A list of date annotations",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TextDateAnnotation"
            }
          }
        },
        "required": [
          "textDateAnnotations"
        ]
      },
      "TextIdAnnotationRequest": {
        "type": "object",
        "description": "A request to annotate IDs in a clinical note",
        "properties": {
          "note": {
            "$ref": "#/components/schemas/Note"
          }
        },
        "required": [
          "note"
        ],
        "example": {
          "note": {
            "identifier": "awesome-note",
            "text": "On 12/26/2020, Ms. Chloe Price met with Dr. Prescott in Seattle. Her SSN is 123-45-6789.\n",
            "type": "loinc:LP29684-5",
            "patientId": "awesome-patient"
          }
        }
      },
      "TextIdAnnotation": {
        "type": "object",
        "description": "An ID annotation in a text",
        "allOf": [
          {
            "$ref": "#/components/schemas/TextAnnotation"
          },
          {
            "type": "object",
            "properties": {
              "idType": {
                "description": "Type of ID information",
                "type": "string",
                "enum": [
                  "account",
                  "bio_id",
                  "device",
                  "health_plan",
                  "id_number",
                  "license",
                  "medical_record",
                  "ssn",
                  "vehicle",
                  "other"
                ]
              }
            },
            "required": [
              "idType"
            ]
          }
        ],
        "example": {
          "start": 42,
          "length": 11,
          "text": "203-11-4535",
          "idType": "ssn",
          "confidence": 95.5
        }
      },
      "TextIdAnnotationResponse": {
        "type": "object",
        "description": "The response to an ID annotation request",
        "properties": {
          "textIdAnnotations": {
            "description": "A list of ID annotations",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TextIdAnnotation"
            }
          }
        },
        "required": [
          "textIdAnnotations"
        ]
      },
      "TextLocationAnnotationRequest": {
        "type": "object",
        "description": "A request to annotate locations in a clinical note",
        "properties": {
          "note": {
            "$ref": "#/components/schemas/Note"
          }
        },
        "required": [
          "note"
        ]
      },
      "TextLocationAnnotation": {
        "type": "object",
        "description": "A location annotation in a text",
        "allOf": [
          {
            "$ref": "#/components/schemas/TextAnnotation"
          },
          {
            "type": "object",
            "properties": {
              "locationType": {
                "description": "Type of location",
                "type": "string",
                "enum": [
                  "city",
                  "country",
                  "department",
                  "hospital",
                  "organization",
                  "other",
                  "room",
                  "state",
                  "street",
                  "zip"
                ]
              }
            },
            "required": [
              "locationType"
            ]
          }
        ],
        "example": {
          "start": 42,
          "length": 7,
          "text": "Seattle",
          "locationType": "city",
          "confidence": 95.5
        }
      },
      "TextLocationAnnotationResponse": {
        "type": "object",
        "description": "The response to a locations annotation request",
        "properties": {
          "textLocationAnnotations": {
            "description": "A list of location annotations",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TextLocationAnnotation"
            }
          }
        },
        "required": [
          "textLocationAnnotations"
        ]
      },
      "TextPersonNameAnnotationRequest": {
        "type": "object",
        "description": "A request to annotate person names in a clinical note",
        "properties": {
          "note": {
            "$ref": "#/components/schemas/Note"
          }
        },
        "required": [
          "note"
        ]
      },
      "TextPersonNameAnnotation": {
        "type": "object",
        "description": "A person name annotation in a text",
        "allOf": [
          {
            "$ref": "#/components/schemas/TextAnnotation"
          }
        ],
        "example": {
          "start": 42,
          "length": 11,
          "text": "Chloe Price",
          "confidence": 95.5
        }
      },
      "TextPersonNameAnnotationResponse": {
        "type": "object",
        "description": "The response to a person names annotation request",
        "properties": {
          "textPersonNameAnnotations": {
            "description": "A list of person name annotations",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TextPersonNameAnnotation"
            }
          }
        },
        "required": [
          "textPersonNameAnnotations"
        ]
      },
      "License": {
        "description": "The license (license keyword used by GitHub)",
        "type": "string",
        "enum": [
          "afl-3.0",
          "apache-2.0",
          "artistic-2.0",
          "bsl-1.0",
          "bsd-2-clause",
          "bsd-3-clause",
          "bsd-3-clause-clear",
          "cc",
          "cc0-1.0",
          "cc-by-4.0",
          "cc-by-sa-4.0",
          "wtfpl",
          "ecl-2.0",
          "epl-1.0",
          "epl-2.0",
          "eupl-1.1",
          "agpl-3.0",
          "gpl",
          "gpl-2.0",
          "gpl-3.0",
          "lgpl",
          "lgpl-2.1",
          "lgpl-3.0",
          "isc",
          "lppl-1.3c",
          "ms-pl",
          "mit",
          "mpl-2.0",
          "osl-3.0",
          "postgresql",
          "ofl-1.1",
          "ncsa",
          "unlicense",
          "zlib",
          "none"
        ],
        "example": "apache-2.0"
      },
      "ToolType": {
        "description": "The type of this tool",
        "type": "string",
        "enum": [
          "nlpsandbox:contact-annotator",
          "nlpsandbox:covid-symptom-annotator",
          "nlpsandbox:data-node",
          "nlpsandbox:date-annotator",
          "nlpsandbox:id-annotator",
          "nlpsandbox:location-annotator",
          "nlpsandbox:person-name-annotator",
          "nlpsandbox:phi-annotator",
          "nlpsandbox:phi-deidentifier"
        ],
        "example": "nlpsandbox:date-annotator"
      },
      "Tool": {
        "type": "object",
        "description": "Information about an NLP tool",
        "properties": {
          "name": {
            "description": "The tool name",
            "type": "string",
            "minLength": 3,
            "maxLength": 60,
            "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          },
          "version": {
            "description": "The version of the tool (SemVer string)",
            "type": "string",
            "minLength": 1,
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          },
          "license": {
            "$ref": "#/components/schemas/License"
          },
          "repository": {
            "description": "The place where the code lives",
            "type": "string"
          },
          "description": {
            "description": "A short, one-sentence summary of the tool",
            "type": "string",
            "maxLength": 280
          },
          "author": {
            "description": "The author of the tool",
            "type": "string"
          },
          "authorEmail": {
            "description": "The email address of the author",
            "type": "string",
            "format": "email"
          },
          "url": {
            "description": "The URL to the homepage of the tool",
            "type": "string",
            "format": "uri"
          },
          "type": {
            "$ref": "#/components/schemas/ToolType"
          },
          "apiVersion": {
            "description": "The version of the tool OpenAPI specification",
            "type": "string",
            "minLength": 1,
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
          }
        },
        "required": [
          "name",
          "version",
          "license",
          "repository",
          "description",
          "author",
          "authorEmail",
          "url",
          "type",
          "apiVersion"
        ],
        "example": {
          "name": "awesome-nlp-tool",
          "version": "1.0.6",
          "license": "apache-2.0",
          "repository": "github:awesome-org/awesome-nlp-tool",
          "description": "An awesome NLP Tool that takes as input X and outputs Y.",
          "author": "Awesome Team",
          "authorEmail": "author@example.com",
          "url": "https://example.com",
          "type": "nlpsandbox:date-annotator",
          "apiVersion": "1.2.0"
        }
      },
      "ToolDependencies": {
        "type": "object",
        "description": "A list of tool dependencies",
        "properties": {
          "tools": {
            "description": "A list of tools",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tool"
            }
          }
        },
        "required": [
          "tools"
        ]
      }
    },
    "responses": {
      "NotFound": {
        "description": "The specified resource was not found",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "InternalServerError": {
        "description": "The request cannot be fulfilled due to an unexpected server error",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "BadRequest": {
        "description": "Invalid request",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      }
    }
  }
}